config/routes.rb
SocialPets::Application.routes.draw do
  devise_for :users
  resources :pets

  root to: 'pets#index'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	validates :name, presence: true
	validates :owner, presence: true
	validates :age, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :owner, :age, :address, :birthdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SocialPets" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">SocialPets</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <!--<li><%= link_to "Link1", "#"  %></li>
              <li><%= link_to "Link2", "#"  %></li>
              <li><%= link_to "Link3", "#"  %></li>-->
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= current_user.email %>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Edit Profile", "#" %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>  
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Not registered yet?", new_user_registration_path %></li>
                <li><%= link_to "Login!", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3 hidden-phone">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <!--<li><%= link_to "Link1", "#"  %></li>
              <li><%= link_to "Link2", "#"  %></li>
              <li><%= link_to "Link3", "#"  %></li>-->
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pets/_form.html.erb
<%= form_for @pet, html: { class: 'form-horizontal' } do |f| %>
  <% if @pet.errors.any? %>
    <div class="accordion alert alert-error" id="accordionErrors">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionErrors" href="#ErrorsList">
            See errors below
          </a>
        </div>
        <div id="ErrorsList" class="accordion-body collapse out">
          <div class="accordion-inner">
            <!--<h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>-->

            <ul>
            <% @pet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
      <!--<div id="error_explanation">
        <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

        <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>-->
    </div>
  <% end %>

  <div class="control-group <%= "error" if @pet.errors.get(:name) %>">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls"><%= f.text_field :name, placeholder: 'Name' %></div>
  </div>
  <div class="control-group <%= "error" if @pet.errors.get(:owner) %>">
    <%= f.label :owner, class: 'control-label' %>
    <div class="controls"><%= f.text_field :owner, placeholder: 'Owner' %></div>
  </div>
  <div class="control-group <%= "error" if @pet.errors.get(:age) %>">
    <%= f.label :age, class: 'control-label' %>
    <div class="controls"><%= f.text_field :age, placeholder: 'Age' %></div>
  </div>
  <div class="control-group">
    <%= f.label :address, class: 'control-label' %>
    <div class="controls"><%= f.text_field :address, placeholder: 'Address' %></div>
  </div>
  <div class="control-group">
    <%= f.label :birthdate, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :birthdate, class: 'input-append' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Save Pet', class: 'btn btn-primary' %>
    <%= link_to 'Back', pets_path, class: 'btn' %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.input-append').datepicker({
      format: 'yyyy-mm-dd'
    });
  });
</script>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Age</th>
      <th class="hidden-phone">Address</th>
      <th class="hidden-phone">Birthdate</th>
      <th class="hidden-phone"></th>
      <th class="hidden-phone"></th>
      <th class="hidden-phone"></th>
      <th class="visible-phone"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td>
          <div class="dropdown">
            <!--<%= link_to pet.name, '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } %>-->
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= pet.name %>
            </a>
            <ul class="dropdown-menu">
              <!-- dropdown menu links -->
              <li><%= link_to 'Show', pet %></li>
              <li><%= link_to 'Edit', edit_pet_path(pet) %></li>
              <li><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </td>
        <td><%= pet.owner %></td>
        <td><%= pet.age %></td>
        <td class="hidden-phone"><%= pet.address %></td>
        <td class="hidden-phone"><%= pet.birthdate %></td>
        <td class="hidden-phone"><%= link_to 'Show', pet, class: 'btn btn-primary' %></td>
        <td class="hidden-phone"><%= link_to 'Edit', edit_pet_path(pet), class: 'btn btn-success' %></td>
        <td class="hidden-phone"><%= link_to 'Destroy', pet, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path, class: 'btn btn-primary' %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @pet.owner %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @pet.address %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @pet.birthdate %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>